# Generated by Django 3.2.9 on 2021-12-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modell', models.CharField(default='RS6', max_length=45, verbose_name='Модель автомобиля')),
            ],
        ),
    ]
