# Generated by Django 3.2.9 on 2021-12-19 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_automobile_body_color_body_type_country_insurance_service_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myhome.brand', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('RWD', 'задний'), ('4WD', 'полный (постоянный и подключаемый)'), ('AWD', 'автоматически подключаемый полный'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'механика'), ('automatic', 'автомат')], default='automatic', max_length=45, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('benzine', 'бензин'), ('electro', 'электро'), ('diesel', 'дизель')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
