# Generated by Django 3.2.9 on 2021-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0006_auto_20211219_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('AWD', 'автоматически подключаемый полный'), ('4WD', 'полный (постоянный и подключаемый)'), ('RWD', 'задний'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image1',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image2',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image3',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image4',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image5',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='interior_color',
            field=models.CharField(choices=[('dark', 'темный'), ('light', 'светлый')], default='dark', max_length=45, verbose_name='Цвет салона'),
        ),
    ]
