# Generated by Django 3.2.9 on 2021-12-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0007_auto_20211219_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobile',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='body_color',
            options={'verbose_name': 'Цвет кузова', 'verbose_name_plural': 'Цвета кузова'},
        ),
        migrations.AlterModelOptions(
            name='body_type',
            options={'verbose_name': 'Тип кузова', 'verbose_name_plural': 'Типы кузова'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Страхование', 'verbose_name_plural': 'Страхование'},
        ),
        migrations.AlterModelOptions(
            name='modell',
            options={'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='type_of_service',
            options={'verbose_name': 'Вид услуги', 'verbose_name_plural': 'Виды услуг'},
        ),
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('FWD', 'передний'), ('AWD', 'автоматически подключаемый полный'), ('RWD', 'задний'), ('4WD', 'полный (постоянный и подключаемый)')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='gearbox',
            field=models.CharField(choices=[('automatic', 'автомат'), ('manual', 'механика')], default='automatic', max_length=45, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image1',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome/static', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image2',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome/static', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image3',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome/static', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image4',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome/static', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='image5',
            field=models.FileField(blank=True, help_text='150x150px', upload_to='myhome/static', verbose_name='Ссылка картинки'),
        ),
    ]
