# Generated by Django 3.2.9 on 2021-12-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0009_auto_20211219_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('FWD', 'передний'), ('4WD', 'полный (постоянный и подключаемый)'), ('RWD', 'задний'), ('AWD', 'автоматически подключаемый полный')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='insurance',
            field=models.ForeignKey(default='1', max_length=200, on_delete=django.db.models.deletion.PROTECT, to='myhome.insurance', verbose_name='Страхование'),
        ),
    ]
