# Generated by Django 3.2.9 on 2021-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0011_auto_20211222_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('RWD', 'задний'), ('4WD', 'полный (постоянный и подключаемый)'), ('FWD', 'передний'), ('AWD', 'автоматически подключаемый полный')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('electro', 'электро'), ('diesel', 'дизель'), ('benzine', 'бензин'), ('hybrid', 'гибрид')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
