# Generated by Django 3.2.9 on 2021-12-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0012_auto_20211222_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна-производитель', 'verbose_name_plural': 'Страны-производители'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='nazvanie',
        ),
        migrations.AddField(
            model_name='service',
            name='nazvanie_id',
            field=models.ForeignKey(default='Audi RS6 2019', on_delete=django.db.models.deletion.PROTECT, to='myhome.automobile', verbose_name='Данные автомобиля'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('4WD', 'полный (постоянный и подключаемый)'), ('RWD', 'задний'), ('AWD', 'автоматически подключаемый полный'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='gearbox',
            field=models.CharField(choices=[('automatic', 'автомат'), ('manual', 'механика')], default='automatic', max_length=45, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='interior_color',
            field=models.CharField(choices=[('light', 'светлый'), ('dark', 'темный')], default='dark', max_length=45, verbose_name='Цвет салона'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('hybrid', 'гибрид'), ('electro', 'электро'), ('benzine', 'бензин'), ('diesel', 'дизель')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(default='Германия', max_length=45, verbose_name='Страна-производитель'),
        ),
    ]
