# Generated by Django 3.2.9 on 2021-12-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0013_auto_20211224_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('FWD', 'передний'), ('RWD', 'задний'), ('4WD', 'полный (постоянный и подключаемый)'), ('AWD', 'автоматически подключаемый полный')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'механика'), ('automatic', 'автомат')], default='automatic', max_length=45, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('benzine', 'бензин'), ('diesel', 'дизель'), ('electro', 'электро'), ('hybrid', 'гибрид')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nazvanie_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='myhome.automobile', verbose_name='Данные автомобиля'),
        ),
    ]
