# Generated by Django 3.2.9 on 2021-12-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0014_auto_20211224_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='nazvanie_id',
        ),
        migrations.AddField(
            model_name='service',
            name='nazvanie',
            field=models.CharField(default='Audi RS6 2019', max_length=65, verbose_name='Данные автомобиля'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('RWD', 'задний'), ('4WD', 'полный (постоянный и подключаемый)'), ('AWD', 'автоматически подключаемый полный'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('diesel', 'дизель'), ('electro', 'электро'), ('benzine', 'бензин'), ('hybrid', 'гибрид')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
