# Generated by Django 3.2.9 on 2021-12-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0015_auto_20211224_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('AWD', 'автоматически подключаемый полный'), ('4WD', 'полный (постоянный и подключаемый)'), ('RWD', 'задний'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='interior_color',
            field=models.CharField(choices=[('dark', 'темный'), ('light', 'светлый')], default='dark', max_length=45, verbose_name='Цвет салона'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('benzine', 'бензин'), ('hybrid', 'гибрид'), ('electro', 'электро'), ('diesel', 'дизель')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
