# Generated by Django 3.2.9 on 2021-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0016_auto_20211224_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('4WD', 'полный (постоянный и подключаемый)'), ('AWD', 'автоматически подключаемый полный'), ('RWD', 'задний'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='interior_color',
            field=models.CharField(choices=[('light', 'светлый'), ('dark', 'темный')], default='dark', max_length=45, verbose_name='Цвет салона'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('diesel', 'дизель'), ('electro', 'электро'), ('benzine', 'бензин'), ('hybrid', 'гибрид')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
