# Generated by Django 3.2.9 on 2021-12-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0018_auto_20211224_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nazvanie',
            field=models.CharField(default='Audi RS6 2019', max_length=65, verbose_name='Данные автомобиля'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('4WD', 'полный (постоянный и подключаемый)'), ('AWD', 'автоматически подключаемый полный'), ('RWD', 'задний'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'механика'), ('automatic', 'автомат')], default='automatic', max_length=45, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='interior_color',
            field=models.CharField(choices=[('light', 'светлый'), ('dark', 'темный')], default='dark', max_length=45, verbose_name='Цвет салона'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('benzine', 'бензин'), ('diesel', 'дизель'), ('electro', 'электро'), ('hybrid', 'гибрид')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
