# Generated by Django 3.2.9 on 2021-12-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0019_auto_20211224_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('AWD', 'автоматически подключаемый полный'), ('RWD', 'задний'), ('FWD', 'передний'), ('4WD', 'полный (постоянный и подключаемый)')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('electro', 'электро'), ('diesel', 'дизель'), ('hybrid', 'гибрид'), ('benzine', 'бензин')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
