# Generated by Django 3.2.9 on 2021-12-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0020_auto_20211224_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='nazvanie',
        ),
        migrations.AlterField(
            model_name='automobile',
            name='drive_unit',
            field=models.CharField(choices=[('AWD', 'автоматически подключаемый полный'), ('4WD', 'полный (постоянный и подключаемый)'), ('RWD', 'задний'), ('FWD', 'передний')], default='RWD', max_length=45, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='interior_color',
            field=models.CharField(choices=[('dark', 'темный'), ('light', 'светлый')], default='dark', max_length=45, verbose_name='Цвет салона'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='type_of_fuel',
            field=models.CharField(choices=[('hybrid', 'гибрид'), ('diesel', 'дизель'), ('benzine', 'бензин'), ('electro', 'электро')], default='benzine', max_length=45, verbose_name='Вид топлива'),
        ),
    ]
